#:kivy 1.10.0
#: import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import utils kivy.utils
#:import Button kivy.uix.button.Button
<FlatButton@ButtonBehavior+Label>:
    font_size: 14
ScreenManager:
    transition : FadeTransition()
    LoginWindow : 
    HomeWindow :
    WelcomeBack :
    RegistWindow :
#:import utils kivy.utils

<FlatButton@ButtonBehavior+Label>:
    font_size: 16

<LoginWindow>:
    id: main_win
    name:'login'
    orientation: "vertical"
    
    canvas.before:
        Color:
            rgba: (1,1,1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'login_bg.png'
    GridLayout:
        cols:2
        FlatButton:
            Image:
                source: 'sisi.png'
                pos: 3,550
                size: 120,40
                allow_stretch: True
            Image:
                source: 'logo_putih.png'
                pos: 40,400
                size: 280,90
                allow_stretch: True
            Label:
                text:'Boosting your Store Perfomance'
                pos: 130,330
                bold: True
                font_size: 17
            Label:
                text:'Posberrry is a Raspberry Pi based Cashier Application'
                pos: 130,300
                bold: True
                font_size: 12
            Label:
                text:'to manage your store easily'
                pos: 130,285
                bold: True
                font_size: 12
        FlatButton:                 
            FlatButton:
                text: 'Welcome to POSBERRY'
                bold: True
                color: utils.get_color_from_hex('#000000')        
                font_size: 30 
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}  
                pos: 530,470
            Label:
                id: info
                markup: True
                size_hint_y: None
                bold:True
                text:''
                font_size:15
                pos: 530,430
            Label:
                
                text:'Username'
                bold:True
                font_size:15
                pos: 382, 400
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 393, 405
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: username_field
                    multiline: False
                    hint_text: "Username"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,408
                    font_size: 13
                    size: 330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
                Image:
                    pos:405,412
                    source:'people.png'
                    size:20,20
            Label:
                text:'Password'
                bold:True
                pos: 380, 327
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,331
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                Image:
                    pos:405,338
                    source:'password.png'
                    size:20,20
                TextInput:
                    id: pwd_field
                    hint_text: "Password"
                    password:True
                    multiline:False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,333
                    font_size: 13
                    size: 330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Change'
                bold:True
                pos: 375, 255
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,258
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                Image:
                    pos:405,262
                    source:'dolar.png'
                    size:20,25
                TextInput:
                    id: money_field
                    multiline:False
                    hint_text: "Change"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,261
                    font_size: 13
                    size:330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            FlatButton:
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#0096FB') 
                    RoundedRectangle:
                        pos: 535, 200
                        size:  84, 34
                        radius: [15, 15, 15, 15]
                Button:
                    on_press: root.validate_user()  
                    pos:537, 203
                    size: 79, 28
                    bold:True
                    font_size:18
                    background_color:0,0,0,0
                    background_normal:''
                    text:'login' 
            GridLayout:
                pos: 500, 120
                cols:2
                size: 200, 25
                orientation:'horizontal'
                spacing:40
                FlatButton:
                    text: 'Do Not have account ?'
                    bold: True
                    color: utils.get_color_from_hex('#000000')        
                    font_size: 15                         
                        
                FlatButton:
                    on_release : app.root.current = "register"
                    on_press: root.loginreset()
                    text: 'Sign Up here'
                    color: utils.get_color_from_hex('#ff0004')  
                    bold: True
                    color: 		    
                    font_size: 15  

<FlatButton@ButtonBehavior+Label>:
    font_size: 16


<RegistWindow>:   
    name:"register"
    namaAwal:FirstName
    namaAkhir:LastName
    usernameku:email
    nomorTelp:PhoneNumber
    passwrd:pass_field
    address:addr_field
    confpasswr:confpass_field
    id: main_win
    orientation: "vertical"
    
    canvas.before:
        Color:
            rgba: (1,1,1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'login_bg.png'
    GridLayout:
        cols:2
        FlatButton:
            Image:
                source: 'sisi.png'
                pos: 3,550
                size: 120,40
                allow_stretch: True
            Image:
                source: 'logo_putih.png'
                pos: 40,400
                size: 280,90
                allow_stretch: True
            Label:
                text:'Boosting your Store Perfomance'
                pos: 130,330
                bold: True
                font_size: 17
            Label:
                text:'Posberrry is a Raspberry Pi based Cashier Application'
                pos: 130,300
                bold: True
                font_size: 12
            Label:
                text:'to manage your store easily'
                pos: 130,285
                bold: True
                font_size: 12
        FlatButton:                 
            FlatButton:
                text: 'Register New Member'
                bold: True
                color: utils.get_color_from_hex('#000000')        
                font_size: 30 
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}  
                pos: 540, 520
            Label:
                id:info_regist
                text:''
                markup: True
                size_hint_y: None
                bold:True
                text:''
                #color: utils.get_color_from_hex('#ff0505')   
                font_size:15
                pos: 540, 490
            Label:
                text:'Username'
                bold:True
                pos: 380, 470
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 393, 477
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: email
                    hint_text: "Username"
                    multiline:False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:398,479
                    font_size: 13
                    size: 362, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'First Name'
                bold:True
                font_size:15
                pos: 382, 400
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 393, 405
                        size:  170, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: FirstName
                    hint_text: "First Name"
                    multiline: False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:398,408
                    font_size: 13
                    size: 165, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Last Name'
                bold:True
                pos: 580, 400
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 593, 405
                        size:  170, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id:LastName
                    hint_text: "Last Name"
                    multiline: False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:600,408
                    font_size: 13
                    size: 165, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Phone Number'
                bold:True
                pos: 395, 327
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,331
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: PhoneNumber
                    multiline: False
                    input_type: 'number'
                    hint_text: "Phone Number"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:397,333
                    font_size: 13
                    size: 362, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Address'
                bold:True
                pos: 375, 255
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,258
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id:addr_field
                    hint_text: "Address"
                    multiline: False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:397,261
                    font_size: 13
                    size: 362, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Password'
                bold:True
                font_size:15
                pos: 380, 120
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 393, 123
                        size:  170, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: pass_field
                    multiline:False
                    hint_text: "Password"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    password:True
                    pos:398,126
                    font_size: 13
                    size: 165, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Gender'
                bold:True
                font_size:15
                pos: 370, 180
                color: utils.get_color_from_hex('#7D7A7A')
            Label:
                text:'Female'               
                font_size:12
                pos: 395, 155
                color: utils.get_color_from_hex('#7D7A7A')
            CheckBox:
                on_active: root.checkboxFemale(self,self.active)
                id:female
                pos: 360, 155
                group:'check'
                color: utils.get_color_from_hex('#7D7A7A')
            
            Label:
                text:'Male'               
                font_size:12
                pos: 488, 155
                color: utils.get_color_from_hex('#7D7A7A')
            CheckBox:
                id:male
                pos: 460, 155
                group:'check'
                color: utils.get_color_from_hex('#7D7A7A')
                on_active: root.checkboxMale(self,self.active)
            Label:
                text:'Confirm Password'
                bold:True
                font_size:15
                pos: 605, 120
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 593, 123
                        size:  170, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: confpass_field
                    multiline: False
                    hint_text: "Confirm Password"
                    password:True
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:600,126
                    font_size: 13
                    size: 165, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            FlatButton:
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#FB3930') 
                    RoundedRectangle:
                        pos: 580, 67
                        size:  84, 34
                        radius: [15, 15, 15, 15]
                Button:   
                    on_press: root.reset()
                    pos: 582,70
                    size: 79, 28
                    bold:True
                    background_color:0,0,0,0
                    background_normal:'' 
                    text:'Reset'
            FlatButton:
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#0096FB') 
                    RoundedRectangle:
                        pos: 677, 67
                        size:  84, 34
                        radius: [15, 15, 15, 15]
                Button:
                    on_press: root.regist()   
                    pos: 680,70
                    size: 79, 28
                    bold:True
                    background_color:0,0,0,0
                    background_normal:'' 
                    text:'Register'
            GridLayout:
                pos: 500, 20
                cols:2
                size: 200, 25
                orientation:'horizontal'
                spacing:40
                FlatButton:
                    text: 'Already have account ?'
                    bold: True
                    color: utils.get_color_from_hex('#000000')        
                    font_size: 15                         
                        
                FlatButton:
                    on_release : app.root.current = "login"
                    text: 'Sign In here'
                    on_press: root.reset()
                    color: utils.get_color_from_hex('#ff0004')  
                    bold: True
                    color: 		    
                    font_size: 15  

#:import utils kivy.utils
<FlatButton@ButtonBehavior+Label>:
    font_size: 14


<WelcomeBack>:
    id: main_win
    name:'welcome'
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1,1,1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
            source: 'registrasi.png'
    GridLayout:
        cols:2
        FlatButton:
            Image:
                source: 'sisi.png'
                pos: 3,550
                size: 120,40
                allow_stretch: True
            Image:
                source: 'logo.png'
                pos: 40,400
                size: 280,90
                allow_stretch: True
            Label:
                text:'Boosting your Business Perfomance'
                pos: 130,330
                bold: True
                font_size: 17
            Label:
                text:'Forca Point Of Sales is an online inventory management'
                pos: 130,300
                bold: True
                font_size: 12
            Label:
                text:'application for cashier and manager store'
                pos: 130,285
                bold: True
                font_size: 12
        FlatButton:                 
            FlatButton:
                text: 'Welcome Back'
                bold: True
                color: utils.get_color_from_hex('#000000')        
                font_size: 40 
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}  
                pos: 530,485
            FlatButton:
                text: 'Sign in to continue'
                bold: True
                color: utils.get_color_from_hex('#0096FB')        
                font_size: 17
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}  
                pos: 530,450
            Label:
                id: info
                markup: True
                size_hint_y: None
                bold:True
                text:''
                font_size:15
                pos: 530,430
            Label:
                text:'Username'
                bold:True
                font_size:15
                pos: 382, 400
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 393, 405
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                TextInput:
                    id: username_field
                    multiline:False
                    hint_text: "Username"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,408
                    font_size: 13
                    size: 330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
                Image:
                    pos:405,412
                    source:'people.png'
                    size:20,20
            Label:
                text:'Password'
                bold:True
                pos: 380, 327
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,331
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                Image:
                    pos:405,338
                    source:'password.png'
                    size:20,20
                TextInput:
                    id: pwd_field
                    hint_text: "Password"
                    password:True
                    multiline:False
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,333
                    font_size: 13
                    size: 330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            Label:
                text:'Change'
                bold:True
                pos: 375, 255
                color: utils.get_color_from_hex('#7D7A7A')    
            FlatButton:
                pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F2EFEF') 
                    RoundedRectangle:
                        pos: 395,258
                        size:  370, 30
                        radius: [13, 13, 13, 13]
                Image:
                    pos:405,262
                    source:'dolar.png'
                    size:20,25
                TextInput:
                    id: money_field
                    hint_text: "Change"
                    background_color: 0,0,0,0  
                    foreground_color: utils.get_color_from_hex('#000000')
                    pos:425,261
                    font_size: 13
                    size:330, 28
                    size_hint: None, None
                    color:utils.get_color_from_hex('#B5B8BC')
                    background_normal:''
            FlatButton:
                #pos_hint: {'center_x': 0.5, 'center_y': -1.5}
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#0096FB') 
                    RoundedRectangle:
                        pos: 535, 200
                        size:  84, 34
                        radius: [15, 15, 15, 15]
                Button:
                    on_press: root.validate_userwelcome()  
                    pos:537, 204
                    size: 79, 28
                    bold:True
                    font_size:18
                    background_color:0,0,0,0
                    background_normal:''
                    text:'login' 
            GridLayout:
                pos: 500, 120
                cols:2
                size: 200, 25
                orientation:'horizontal'
                spacing:50
                FlatButton:
                    text: 'Do Not have account ?'
                    bold: True
                    color: utils.get_color_from_hex('#000000')        
                    font_size: 15                         
                        
                FlatButton:
                    on_release: app.root.current = "register"
                    on_press: root.loginreset()
                    text: 'Sign Up here'
                    color: utils.get_color_from_hex('#ff0004')  
                    bold: True
                    color: 		    
                    font_size: 15   

<HomeWindow>:
    waktu:waktu
    jam:jam
    id: main_win
    name: 'Home_Win'
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: (1,1,1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    BoxLayout:
        orientation:'vertical'
        GridLayout:
            cols:3
            id: header
            size_hint_y: None
            height: 60
            canvas.before:
                Color:
                    rgba: utils.get_color_from_hex('#81CCFE')
                Rectangle:
                    size: self.size
                    pos: self.pos 
            BoxLayout:
                orientation:'horizontal'
                BoxLayout:
                    size_hint_x: .1
                    Button:
                        background_color: utils.get_color_from_hex('#81CCFE')
                        background_normal:''

                        #on_press:root.setName(*args)
                        #on_press: root.list_data() 
                        Image:
                            source: 'sisi.png'
                            center_x: self.parent.center_x
                            center_y: self.parent.center_y
                            size:90,90
                            allow_stretch: True
                BoxLayout:
                    size_hint_x:.2
            BoxLayout:
                size_hint_x: .4
                Button:
                    background_color: 0,0,0,0
                    background_normal:''

                        #on_press:root.setName(*args)
                        #on_press: root.list_data() 
                    Image:
                        source: 'logo_putih.png'
                        center_x: self.parent.center_x
                        center_y: self.parent.center_y
                        size:180,180
                        allow_stretch: True       
            BoxLayout:
                #spacing:5
                BoxLayout:
                    size_hint_x:.6
                Button:
                    background_color: utils.get_color_from_hex('#81CCFE')
                    background_normal:''
                    size_hint_x: .2
                    on_press:root.logout(*args)
                    #on_press: root.list_data() 
                    Image:
                        source: 'woman.png'
                        center_x: self.parent.center_x
                        center_y: self.parent.center_y
                        size: 60,60
                        allow_stretch: True

        BoxLayout:
            padding:5
            BoxLayout:
                id: product_details
                orientation: "vertical"
                size_hint_x: .3
                
                BoxLayout:
                    orientation:"horizontal"
                    size_hint_y: .1
                    TextInput:
                        hint_text: "Name/ Product Code"
                        id: qty_inp_scan
                        size_hint_x: .7
                        foreground_color:utils.get_color_from_hex('#000000')  
                        background_color:0,0,0,0
                        multiline: False
                        on_text_validate: root.list_data() 
                    Button:
                        background_color: utils.get_color_from_hex('#EBE7E7')  
                        background_normal:''
                        size_hint_x: .1
                        #on_press: root.list_data() 
                        Image:
                            source: 'add.png'
                            center_x: self.parent.center_x
                            center_y: self.parent.center_y
                            size: 20, 20
                            allow_stretch: True
                BoxLayout:
                    id: add_to_cart
                    orientation: 'vertical'
                    size_hint_y: .8
                    BoxLayout:    
                        size_hint_y: None
                        height: 30
                        canvas.before:
                            Color:
                                rgb: utils.get_color_from_hex('#0099FF')
                            Rectangle:
                                size: self.size
                                pos: self.pos
                        Label:
                            bold:True
                            text: 'Product'
                            size_hint_x: .3
                        Label:
                            bold:True
                            text: 'Price'
                            size_hint_x: .2
                        Label:
                            bold:True
                            text: 'Qty'
                            size_hint_x: .1
                        Label:
                            bold:True
                            text: 'Subtotal'
                            size_hint_x: .2
                    
                    TextInput:
                        id: list_item
                        readonly: True
                        hint_text:'Enter text'
                        text:root.listbarang#mengclear text input melalui class lain
                        pos_hint: {'center_x': 0.5, 'center_y': -1.5} 
                        size_hint: 1, 4
                       
                    
                BoxLayout:
                    orientation:"horizontal"
                    size_hint_y: .1
                    canvas.before:
                        Color:
                            rgb: utils.get_color_from_hex('#F57F0A')
                        Rectangle:
                            size: self.size
                            pos: self.pos
                    BoxLayout:
                        orientation:'horizontal'
                        TextInput:
                            text: "Items"
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            #size_hint_x:.3
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        TextInput:
                            text: "0"
                            halign:'right'
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            size_hint_x:.2
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        
                                
                    BoxLayout:
                        orientation:'horizontal'
                        TextInput:
                            text: "Total"
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            #size_hint_x:.3
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        TextInput:

                            text: "0"
                            halign:'right'
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            size_hint_x:.2
                            readonly: True
                            id: totalharga
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        
                                
                BoxLayout:
                    orientation:"vertical"
                    size_hint_y: .2
                    canvas.before:
                        Color:
                            rgb: utils.get_color_from_hex('#D2E1F8')
                        Rectangle:
                            size: self.size
                            pos: self.pos
                    BoxLayout:
                        orientation:'horizontal'
                        TextInput:
                            text: "Total Payable"
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        TextInput:
                            text: "0.0"
                            halign:'right'
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            size_hint_x:.2
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                    BoxLayout:
                        orientation:'horizontal'
                        TextInput:
                            text: "Cash"
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            size_hint_x:.5
                            readonly: True
                            multiline:False
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        TextInput:
                        
                            hint_text: "0.0"
                            font_size: 14
                            text_size: self.size
                            halign:'right'
                            multiline:False
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                    BoxLayout:
                        orientation:'horizontal'
                        TextInput:
                            text: "Change"
                            color:utils.get_color_from_hex('#000000')
                            font_size: 14
                            text_size: self.size
                            size_hint_x:.5
                            readonly: True
                            id: qty_inp
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        TextInput:
                        
                            hint_text: "0.0"
                            font_size: 14
                            text_size: self.size
                            halign:'right'
                            background_color: 0,0,0,0  
                            foreground_color: utils.get_color_from_hex('#000000')
                        
                                
                BoxLayout:
                    orientation:"horizontal"
                    size_hint_y: .1
                    spacing:5
                    padding:5
                    BoxLayout:   
                    BoxLayout: 
                    BoxLayout:    
                        size_hint_x:.8   
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex('#F60A0A') 
                            RoundedRectangle:
                                pos: self.pos
                                size:self.size
                                radius: [15, 15, 15, 15]
                        Button:   
                            bold:True
                            font_size:15
                            background_color:0,0,0,0
                            background_normal:'' 
                            text:'Cancel'
                            pos:self.pos
                            color:utils.get_color_from_hex('#ffffff') 
                    BoxLayout:
                        size_hint_x:.8 
                        canvas:
                            Color:
                                rgba: utils.get_color_from_hex('#0096FB') 
                            RoundedRectangle:
                                pos: self.pos
                                size:self.size
                                radius: [15, 15, 15, 15]
                        Button:   
                            bold:True
                            font_size:15
                            background_color:0,0,0,0
                            background_normal:'' 
                            text:'OK'
                            pos:self.pos
                            color:utils.get_color_from_hex('#ffffff') 
            BoxLayout:
                orientation: "vertical"
                size_hint_x:.4 
                Accordion:
                    orientation:'vertical'
                    size_hint_y:.2
                    AccordionItem: 
                        title: 'Produk Makanan'
                        size_hint_y:.1
                        ScrollView:
                            pos_hint: {"top": 1, "left": 1}
                            size_hint: 1, .95
                            GridLayout:
                                # Banner grid
                                id: friend_banner_grid
                                cols: 3
                                spacing: 10,10
                                size_hint_y: None
                                height: self.minimum_height
                                row_default_height: '100dp'                 
                                spacing:5
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'BENG-BENG'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'beng_beng.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,100
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                        
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'NEXTAR'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'nextar.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,80
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                        
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'OREO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'oreo.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,100
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TARO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'taro.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'LAYS'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'lays.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'SLAY OLAI'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'slay.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,90
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'POTA BEE'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'pota_bee.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,60
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'CHITATO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'chitato.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,80
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'ROMA KELAPA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'roma.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,60
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'SARI GANDUM'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'sari_gandum.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,95
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'RIN BEE'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'rinbee.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'SPONGE'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'sponge.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,60
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TANGO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'tango.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,90
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'SIIP'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'siip.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,60
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'GERY SALUT'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'gery_salut.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,80
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'CRISPY CRACKERS'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'crispy.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,80
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 2500'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                    AccordionItem: 
                        title: 'Produk Minuman'
                        size_hint_y:.1
                        ScrollView:
                            pos_hint: {"top": 1, "left": 1}
                            size_hint: 1, .91
                            GridLayout:
                                # Banner grid
                                id: friend_banner_grid
                                cols: 3
                                spacing: 10,10
                                size_hint_y: None
                                height: self.minimum_height
                                row_default_height: '100dp'
                                
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'FRESTEA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos
                                                
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'frestea.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,150
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')  
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'GOOD DAY'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'goodday.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'ICHI OCHA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'ichi.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'LE MINERALE'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'leminerale.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'MINUTE MAID'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'minute_maid.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:100,100
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TEH PUCUK'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'teh_pucuk.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TEH KOTAK'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'teh_kotak.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'ULTRAMILK'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'ultramilk.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'FRUIT TEA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'fruit_tea.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                            
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'FRUIT TEA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'fruittea.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'AQUA'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'aqua.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'CLEO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'cleo.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TEH GELAS'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'teh_gelas.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'HYDRO COCO'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'hydro.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
                                BoxLayout:                         
                                    orientation:'vertical'
                                    canvas.before:
                                        Color:
                                            rgba: utils.get_color_from_hex('#f0f1f2')
                                        RoundedRectangle:
                                            size: self.size
                                            pos: self.pos
                                            radius:0,0,30,0
                                    Label:
                                        text:'TEH BOTOL'
                                        font_size:14
                                        halign:'center'
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#454444')
                                        canvas.before:
                                            Color:
                                                rgba: utils.get_color_from_hex('#d4d4d4')
                                            Rectangle:
                                                size: self.size
                                                pos: self.pos    
                                    Button:
                                        size_hint_y:.3
                                        font_size: 14
                                        text_size: self.size     
                                        halign: 'center'
                                        valign:'top'
                                        padding_y:3
                                        background_color: utils.get_color_from_hex('#f0f1f2')
                                        background_normal:''
                                        font_size:12
                                        Image:
                                            valign:'top'
                                            source: 'teh_botol.png'
                                            center_x: self.parent.center_x
                                            center_y: self.parent.center_y
                                            size:70,70
                                            keep_ratio: True
                                            allow_stretch: True
                                    Label:
                                        text:'Rp 6000'
                                        font_size:12
                                        size_hint_y:.1
                                        color:utils.get_color_from_hex('#042f59')
<SetNamePopup>: 
    title:'Logout'
    size_hint:.5,.5
    auto_dismiss: False
    BoxLayout:  
        canvas.before:
            Color:
                rgba: utils.get_color_from_hex('#ffffff')  
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius:5,5,5,5
        orientation:'vertical'
        spacing:5
        BoxLayout:
            
            Label:
                font_size:20
                align:'center'
                text:'Are you sure ?'
                color: utils.get_color_from_hex('#000000') 
        BoxLayout: 
            orientation:'horizontal'
            size_hint_y:.2  
            spacing:30
            BoxLayout:
                size_hint_x:.7
            BoxLayout:   
                size_hint_x:.2
                padding:10
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#F60A0A') 
                    RoundedRectangle:
                        pos: self.pos
                        size:self.size
                        radius: [15, 15, 15, 15]
                Button:   
                    bold:True
                    font_size:13
                    background_color:0,0,0,0
                    background_normal:'' 
                    text:'NO'
                    pos:self.pos
                    on_press: root.FadePopup()
                    color:utils.get_color_from_hex('#ffffff')
                    #on_release : app.root.current = "register"
            BoxLayout:   
                size_hint_x:.2
                padding:10
                canvas:
                    Color:
                        rgba: utils.get_color_from_hex('#0096FB') 
                    RoundedRectangle:
                        pos: self.pos
                        size:self.size
                        radius: [15, 15, 15, 15]
                Button:   
                    bold:True
                    font_size:13
                    background_color:0,0,0,0
                    background_normal:'' 
                    text:'YES'
                    on_press: root.FadePopup()
                    #on_press: root.reset()
                    on_press: app.root.current = "login"
                    pos:self.pos
                    color:utils.get_color_from_hex('#ffffff') 
            BoxLayout:
                size_hint_x:.1
        BoxLayout:

            size_hint_y:.3
   
<ProfileWindow>: 
    title:'Profile'
    size_hint:.5,.8
    auto_dismiss: False
    BoxLayout: 
        orientation:'vertical'
        #spacing:10
        canvas.before:
            Color:
                rgba: utils.get_color_from_hex('#ffffff')  
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius:5,5,5,5
        BoxLayout:
            orientation:'horizontal'
            size_hint_y:.1
            padding:5
            spacing:10
            BoxLayout:
                size_hint_x:.9
            BoxLayout:
                size_hint_x:.1
                Button:
                    #pos:self.pos
                    background_color:0,0,0,0
                    background_normal:'' 
                    on_press: root.FadePopup() 
                    Image:
                        size_hint_x:.4
                        source: 'remove.png'
                        center_x: self.parent.center_x
                        center_y: self.parent.center_y
                        size: 25,25
                        allow_stretch: True
        BoxLayout:
            size_hint_y:.3
            background_color: utils.get_color_from_hex('#81CCFE')
                #on_press:root.setName(*args)
                #on_press: root.list_data() 
            Image:
                valign:'top'
                source: 'woman_logout.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y
                size:100,100
                keep_ratio: True
                allow_stretch: True
            #pos:self.pos
        BoxLayout:
            size_hint_y:.2
            Label:
                font_size:25
                bold:True
                text:'Uswatun Hasanah'
                color: utils.get_color_from_hex('#000000')
        BoxLayout:
            #pos:self.pos
            size_hint_y:.2
            GridLayout:
                cols:4
                BoxLayout:
                    size_hint_x:.2
                BoxLayout:
                    size_hint_x:.2
                    Button:
                        #pos:self.pos
                        background_color:0,0,0,0
                        background_normal:'' 
                            #on_press:root.setName(*args)
                            #on_press: root.list_data() 
                        Image:
                            size_hint_x:.4
                            source: 'koin.png'
                            center_x: self.parent.center_x
                            center_y: self.parent.center_y
                            size: 40,40
                            allow_stretch: True
                BoxLayout:
                    size_hint_x:.5
                    orientation:'vertical'
                    TextInput:
                        background_color: 0,0,0,0
                        foreground_color: utils.get_color_from_hex('#000000')
                        text:'100 penjualan'
                        color: utils.get_color_from_hex('#000000')
                        halign: 'left'
                        readonly: True
                        multiline:False
                    TextInput:
                        background_color: 0,0,0,0
                        foreground_color: utils.get_color_from_hex('#000000')
                        readonly: True
                        halign: 'left'
                        text:'Rp 5.000.000,00'
                        color: utils.get_color_from_hex('#000000')
                        multiline:False
                BoxLayout:

                    size_hint_x:.1
        GridLayout:
            #pos:self.pos
            size_hint_y:.5
            cols:3
            BoxLayout:
                size_hint_x:.1
            BoxLayout:
                padding:60
                size_hint_x:.3
                BoxLayout:
                    canvas:
                        Color:
                            rgba: utils.get_color_from_hex('#F60A0A') 
                        RoundedRectangle:
                            pos: self.pos
                            size:  self.size
                            radius: [20, 20, 20, 20]
                    Button:   
                        bold:True
                        font_size:15
                        background_color:0,0,0,0 
                        background_normal:'' 
                        text:'Logout'
                        pos:self.pos
                        color:utils.get_color_from_hex('#ffffff')
                        border: (5,5,5,5)
                        
            BoxLayout:
                size_hint_x:.1
                
